// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

// SubNamespaceMoveSpecApplyConfiguration represents a declarative configuration of the SubNamespaceMoveSpec type for use
// with apply.
//
// SubNamespaceMoveSpec defines a move between parent namespaces.
type SubNamespaceMoveSpecApplyConfiguration struct {
	// SourceParent is the current parent namespace of the sub-namespace.
	SourceParent *string `json:"sourceParent,omitempty"`
	// TargetParent is the desired parent namespace of the sub-namespace.
	TargetParent *string `json:"targetParent,omitempty"`
}

// SubNamespaceMoveSpecApplyConfiguration constructs a declarative configuration of the SubNamespaceMoveSpec type for use with
// apply.
func SubNamespaceMoveSpec() *SubNamespaceMoveSpecApplyConfiguration {
	return &SubNamespaceMoveSpecApplyConfiguration{}
}

// WithSourceParent sets the SourceParent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceParent field is set to the value of the last call.
func (b *SubNamespaceMoveSpecApplyConfiguration) WithSourceParent(value string) *SubNamespaceMoveSpecApplyConfiguration {
	b.SourceParent = &value
	return b
}

// WithTargetParent sets the TargetParent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetParent field is set to the value of the last call.
func (b *SubNamespaceMoveSpecApplyConfiguration) WithTargetParent(value string) *SubNamespaceMoveSpecApplyConfiguration {
	b.TargetParent = &value
	return b
}
