// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v2

// SubNamespaceSpecApplyConfiguration represents a declarative configuration of the SubNamespaceSpec type for use
// with apply.
//
// SubNamespaceSpec defines the desired state of SubNamespace
type SubNamespaceSpecApplyConfiguration struct {
	// Labels are the labels to be propagated to the sub-namespace
	Labels map[string]string `json:"labels,omitempty"`
	// Annotations are the annotations to be propagated to the sub-namespace.
	Annotations map[string]string `json:"annotations,omitempty"`
}

// SubNamespaceSpecApplyConfiguration constructs a declarative configuration of the SubNamespaceSpec type for use with
// apply.
func SubNamespaceSpec() *SubNamespaceSpecApplyConfiguration {
	return &SubNamespaceSpecApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SubNamespaceSpecApplyConfiguration) WithLabels(entries map[string]string) *SubNamespaceSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SubNamespaceSpecApplyConfiguration) WithAnnotations(entries map[string]string) *SubNamespaceSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
