version: 2
builds:
  - id: kubectl-accurate
    main: ./cmd/kubectl-accurate
    binary: kubectl-accurate
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cybozu-go/accurate.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    ignore: # ref: https://goreleaser.com/deprecations/#builds-for-windowsarm64
      - goos: windows
        goarch: arm64

archives:
  - ids:
      - kubectl-accurate
    name_template: "kubectl-{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: [ 'tar.gz' ]
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  github:
    owner: cybozu-go
    name: accurate
  prerelease: auto
  name_template: "Release {{ .Tag }}"
