apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: accurate
spec:
  version: {{ .TagName }}
  homepage: https://github.com/cybozu-go/accurate
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/cybozu-go/accurate/releases/download/{{ .TagName }}/kubectl-accurate_{{ .TagName }}_darwin_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-accurate
      files:
        - from: kubectl-accurate
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/cybozu-go/accurate/releases/download/{{ .TagName }}/kubectl-accurate_{{ .TagName }}_darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-accurate
      files:
        - from: kubectl-accurate
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/cybozu-go/accurate/releases/download/{{ .TagName }}/kubectl-accurate_{{ .TagName }}_linux_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-accurate
      files:
        - from: kubectl-accurate
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/cybozu-go/accurate/releases/download/{{ .TagName }}/kubectl-accurate_{{ .TagName }}_linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-accurate
      files:
        - from: kubectl-accurate
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/cybozu-go/accurate/releases/download/{{ .TagName }}/kubectl-accurate_{{ .TagName }}_windows_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-accurate.exe
      files:
        - from: kubectl-accurate.exe
          to: .
        - from: LICENSE
          to: .
  shortDescription: Accurate is a Kubernetes controller for multi-tenancy.
  description: |
    kubectl-accurate is a subcommand of kubectl to manage Accurate features.
    Accurate is a Kubernetes controller for multi-tenancy.
    It propagates resources between namespaces accurately and allows tenant users to create/delete sub-namespaces.
    Read more documentation at: https://cybozu-go.github.io/accurate/index.html
