name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.51.2
        policy_allow: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
