name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.3
        policy_allow: "true"
        github_token: ${{ inputs.github_token }}
