name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
permissions:
  contents: read
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make release-build
  test:
    name: Small tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make lint
    - run: make test
    - run: make check-generate
    - run: make envtest
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version:
        - v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5 # renovate: kindest/node
        - v1.35.5@sha256:ce977ae6d65918d0b58a5f8b5e940429c2ce42fa3a5619ec2bbc60b949c0ac95 # renovate: kindest/node
        - v1.34.8@sha256:02722c2dedddcfc00febf5d27fbeb9b7b2c14294c82109ff4a85d89ac9ba3256 # renovate: kindest/node
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        cache: true
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make start KUBERNETES_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - name: Sanitize version name
      id: sanitize
      run: |
        # extract only version name because ':' is not allowed for artifact name
        SANITIZED_K8S_VERSION="$(echo ${{ matrix.k8s-version}} | awk -F '@' '{print $1}')"
        echo "SANITIZED_K8S_VERSION=$SANITIZED_K8S_VERSION" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: logs-${{ steps.sanitize.outputs.SANITIZED_K8S_VERSION }}.tar.gz
        path: e2e/logs.tar.gz
