name: Pinact
on:
  pull_request:
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
jobs:
  verify-pinact:
    name: Verify pinned GitHub Actions comments
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/aqua
      - name: Verify SHAs and tag comments are consistent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pinact run --check --verify-comment
