name: Renovate
on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # renovate v46.1.6
        with:
          configurationFile: config.json
          token: ${{ steps.app-token.outputs.token }}
